/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as ModelsRouteImport } from './app/models'
import { Route as ActivityRouteImport } from './app/activity'
import { Route as PageRouteImport } from './app/page'
import { Route as ConfigurationPageRouteImport } from './app/configuration/page'

const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const PageRoute = PageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationPageRoute = ConfigurationPageRouteImport.update({
  id: '/configuration/',
  path: '/configuration/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PageRoute
  '/activity': typeof ActivityRoute
  '/models': typeof ModelsRoute
  '/configuration/': typeof ConfigurationPageRoute
}
export interface FileRoutesByTo {
  '/': typeof PageRoute
  '/activity': typeof ActivityRoute
  '/models': typeof ModelsRoute
  '/configuration': typeof ConfigurationPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof PageRoute
  '/activity': typeof ActivityRoute
  '/models': typeof ModelsRoute
  '/configuration/': typeof ConfigurationPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/activity' | '/models' | '/configuration/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/activity' | '/models' | '/configuration'
  id: '__root__' | '/' | '/activity' | '/models' | '/configuration/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PageRoute: typeof PageRoute
  ActivityRoute: typeof ActivityRoute
  ModelsRoute: typeof ModelsRoute
  ConfigurationPageRoute: typeof ConfigurationPageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuration/': {
      id: '/configuration/'
      path: '/configuration'
      fullPath: '/configuration/'
      preLoaderRoute: typeof ConfigurationPageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  PageRoute: PageRoute,
  ActivityRoute: ActivityRoute,
  ModelsRoute: ModelsRoute,
  ConfigurationPageRoute: ConfigurationPageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
