name: Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      release_name:
        description: "Name of the release"
        required: true
        type: string
  workflow_call:
    inputs:
      release_name:
        description: "Name of the release"
        required: true
        type: string

permissions:
  contents: write

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      max-parallel: 2
      matrix:
        include:
          - runner: ubuntu-24.04
            arch: amd64
          - runner: ubuntu-24.04-arm
            arch: arm64

    steps:
      - uses: actions/checkout@v6

      - name: Install system dependencies
        if: contains(matrix.runner, 'ubuntu')
        run: |
          sudo apt update
          sudo apt install -y librsvg2-dev libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev libpam0g-dev libv4l-dev fprintd rpm nasm

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo registry
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.arch }}-cargo-${{ hashFiles('Cargo.lock') }}
          restore-keys: ${{ runner.os }}-${{ matrix.arch }}-cargo-

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Extract Version
        id: get_version
        run: |
          if [ -n "${{ inputs.release_name }}" ]; then
            VERSION="${{ inputs.release_name }}"
          else
            VERSION="${{ github.ref_name }}"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Update Cargo.toml version
        run: |
          echo "Updating Cargo.toml version to ${{ steps.get_version.outputs.version }}"
          sed -i -e "0,/^version = \".*\"/s//version = \"${{ steps.get_version.outputs.version }}\"/" Cargo.toml
          cat Cargo.toml

      - name: Build & package
        run: |
          rm -rf target/release/bundle/
          cargo build --release --package biopass-auth --package biopass-pam
          cd apps/desktop
          bun install --frozen-lockfile
          bun run tauri build
          cd ../..
          ls -R target/release/bundle/

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.get_version.outputs.version }}
          name: ${{ steps.get_version.outputs.version }}
          prerelease: ${{ contains(steps.get_version.outputs.version, 'rc') || contains(steps.get_version.outputs.version, 'beta') }}
          files: |
            target/release/bundle/deb/*.deb
            target/release/bundle/rpm/*.rpm
